"""add_modular_pipeline_schema

Revision ID: 734a2e0f842d
Revises: 87151021f090
Create Date: 2026-03-31 09:41:39.166026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '734a2e0f842d'
down_revision: Union[str, Sequence[str], None] = '87151021f090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fertilizer_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('price_per_50kg', sa.Float(), nullable=True),
    sa.Column('scrape_date', sa.Date(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'company', 'scrape_date', name='uq_price_product_company_date')
    )
    op.create_index('idx_price_product_date', 'fertilizer_prices', ['product_id', 'scrape_date'], unique=False)
    op.create_index(op.f('ix_fertilizer_prices_scrape_run_id'), 'fertilizer_prices', ['scrape_run_id'], unique=False)
    op.create_table('scrape_anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=False),
    sa.Column('parser_id', sa.String(length=50), nullable=False),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomaly_run_parser', 'scrape_anomalies', ['scrape_run_id', 'parser_id'], unique=False)
    op.create_table('section_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=False),
    sa.Column('subsection_id', sa.String(length=50), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'subsection_id', name='uq_section_subsection')
    )
    op.add_column('blocks', sa.Column('name_en', sa.String(length=200), nullable=True))
    op.add_column('districts', sa.Column('name_en', sa.String(length=200), nullable=True))
    op.add_column('scrape_checkpoints', sa.Column('parser_id', sa.String(length=50), nullable=True))
    op.add_column('scrape_checkpoints', sa.Column('work_unit_key', sa.String(length=200), nullable=True))
    op.alter_column('scrape_checkpoints', 'district_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('scrape_checkpoints', 'block_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index('idx_checkpoint_generic', 'scrape_checkpoints', ['scrape_run_id', 'parser_id', 'work_unit_key'], unique=False)
    op.add_column('scrape_runs', sa.Column('section_id', sa.String(length=50), nullable=True))
    op.add_column('scrape_runs', sa.Column('subsection_id', sa.String(length=50), nullable=True))
    op.add_column('scrape_runs', sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'source_updated_at')
    op.drop_column('scrape_runs', 'subsection_id')
    op.drop_column('scrape_runs', 'section_id')
    op.drop_index('idx_checkpoint_generic', table_name='scrape_checkpoints')
    op.alter_column('scrape_checkpoints', 'block_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('scrape_checkpoints', 'district_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('scrape_checkpoints', 'work_unit_key')
    op.drop_column('scrape_checkpoints', 'parser_id')
    op.drop_column('districts', 'name_en')
    op.drop_column('blocks', 'name_en')
    op.drop_table('section_metadata')
    op.drop_index('idx_anomaly_run_parser', table_name='scrape_anomalies')
    op.drop_table('scrape_anomalies')
    op.drop_index(op.f('ix_fertilizer_prices_scrape_run_id'), table_name='fertilizer_prices')
    op.drop_index('idx_price_product_date', table_name='fertilizer_prices')
    op.drop_table('fertilizer_prices')
    # ### end Alembic commands ###
