"""rename name_ta to name for districts, blocks, dealers

Revision ID: bbe3617efcd2
Revises: 530819517819
Create Date: 2026-03-31 15:18:50.436799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe3617efcd2'
down_revision: Union[str, Sequence[str], None] = '530819517819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('name', sa.String(length=200), nullable=False))
    op.alter_column('blocks', 'name_ta',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('blocks', 'name_en')
    op.add_column('dealers', sa.Column('name', sa.String(length=300), nullable=False))
    op.drop_column('dealers', 'name_ta')
    op.add_column('districts', sa.Column('name', sa.String(length=200), nullable=False))
    op.alter_column('districts', 'name_ta',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('districts', 'name_en')
    op.drop_index(op.f('idx_checkpoint_generic'), table_name='scrape_checkpoints')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_checkpoint_generic'), 'scrape_checkpoints', ['scrape_run_id', 'parser_id', 'work_unit_key'], unique=False)
    op.add_column('districts', sa.Column('name_en', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.alter_column('districts', 'name_ta',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('districts', 'name')
    op.add_column('dealers', sa.Column('name_ta', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('dealers', 'name')
    op.add_column('blocks', sa.Column('name_en', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.alter_column('blocks', 'name_ta',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('blocks', 'name')
    # ### end Alembic commands ###
