"""add seed_stocks table

Revision ID: c4e5d1f2a8b3
Revises: bbe3617efcd2
Create Date: 2026-03-31 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e5d1f2a8b3'
down_revision: Union[str, Sequence[str], None] = ('bbe3617efcd2', '77eae4d502b9')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: add seed_stocks table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'seed_stocks',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('scrape_run_id', sa.Integer(), nullable=True),
        sa.Column('district_code', sa.String(length=20), nullable=False),
        sa.Column('district_name', sa.String(length=200), nullable=True),
        sa.Column('block_code', sa.String(length=20), nullable=False),
        sa.Column('block_name', sa.String(length=200), nullable=True),
        sa.Column('source_type', sa.String(length=20), nullable=False),
        sa.Column('crop_name', sa.String(length=200), nullable=False),
        sa.Column('crop_variety', sa.String(length=200), nullable=True),
        sa.Column('agency_name', sa.String(length=300), nullable=True),
        sa.Column('quantity_available', sa.Float(), nullable=True),
        sa.Column('unit', sa.String(length=20), nullable=True),
        sa.Column('season', sa.String(length=100), nullable=True),
        sa.Column('scrape_date', sa.Date(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'idx_seed_date_block',
        'seed_stocks',
        ['scrape_date', 'block_code'],
        unique=False
    )
    op.create_index(
        'idx_seed_source_type',
        'seed_stocks',
        ['source_type'],
        unique=False
    )
    op.create_index(
        'ix_seed_stocks_scrape_run_id',
        'seed_stocks',
        ['scrape_run_id'],
        unique=False
    )
    op.create_unique_constraint(
        'uq_seed_block_crop_agency_date',
        'seed_stocks',
        ['block_code', 'crop_name', 'crop_variety', 'agency_name', 'source_type', 'scrape_date']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: drop seed_stocks table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_seed_block_crop_agency_date',
        'seed_stocks',
        type_='unique'
    )
    op.drop_index(
        'ix_seed_stocks_scrape_run_id',
        table_name='seed_stocks'
    )
    op.drop_index(
        'idx_seed_source_type',
        table_name='seed_stocks'
    )
    op.drop_index(
        'idx_seed_date_block',
        table_name='seed_stocks'
    )
    op.drop_table('seed_stocks')
    # ### end Alembic commands ###
